# Generated by Django 4.1.3 on 2022-11-25 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='file_types',
            field=models.CharField(default='.zip', max_length=100),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='file_types',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='marks',
            field=models.TextField(default='NA'),
        ),
    ]
