# Generated by Django 4.1.3 on 2022-11-27 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='autograder',
            new_name='tree',
        ),
    ]
